
server:
  port: 8080

knife4j:
  enable: true
  openapi:
    title: aichat的api文档
#    description: "'我是测试',**你知道吗**
## aaa"
#    email: xiaoymin@foxmail.com
#    concat: 八一菜刀
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: ai脑筋急转弯
        api-rule: package
        api-rule-resources:
          - com.sw.aichat.controller

ai:
  apiKey: 0c7aa08f-334b-45d3-ae18-a7f419d8345f
